blog/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
	url(r'^$', 'blog.views.home', name='home'),
	url(r'^contacto/$', 'blog.views.contacto', name='contacto'),
	url(r'^conversor/$', 'blog.views.conversor', name='conversor'),
	url(r'^calcu/$', 'blog.views.calcu', name='calcu'),
	url(r'^crono/$', 'blog.views.crono', name='crono'),
	url(r'^curriculum/$', 'blog.views.curriculum', name='curriculum'),
	url(r'^ver_post/(?P<id_post>[0-9]+)/$', 'blog.views.ver_post', name='vermipost'),
	#url(r'^mensaje/$', 'blog.views.mensaje', name='mensaje'),
	url(r'^contacto/$', 'blog.views.contacto', name='contacto'),
	url(r'^comentar/$', 'blog.views.comentar', name='comentar'),
)

problog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('blog.urls', namespace = "app_blog")),
    url(r'^admin/', include(admin.site.urls)),
	
]

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.

class Entrada(models.Model):
	class Meta:
		verbose_name = "Mi Entrada"
		verbose_name_plural = "Todas mis entradas"
		ordering=['-fecha']

	titulo = models.CharField(u'Título', max_length=100)
	fecha = models.DateTimeField(u'Fecha del Post',auto_now_add=True)
	resumen= models.CharField(u'Resumen',max_length=512)
	contenido = models.TextField(u'Contenido')

	def __str__(self):
		return self.titulo


class Mensajes(models.Model):
	class Meta:
		verbose_name = "Mensaje"
		verbose_name_plural = "Todos los mensajes"
		ordering=['-fecha']
	nombre= models.CharField(u'Nombre', max_length=70)
	fecha = models.DateTimeField(u'Fecha del comentario',auto_now_add=True)
	published = models.BooleanField(u'Publicado?', default=True)
	mensaje= models.TextField(u'Mensaje')
	published_in = models.ForeignKey(Entrada)
	def __str__(self):
		return self.nombre

blog/views.py
from django.template import RequestContext
from django.shortcuts import render_to_response, render, redirect
from blog.models import Entrada, Mensajes
from django.http import HttpResponse
from django.core.mail import EmailMessage
from django.core.mail import EmailMessage
import json

# Create your views here.
def home(request):
	context = RequestContext(request)
	posts = Entrada.objects.all()
	return render_to_response('SitioWebHoshible.html',{'posts':posts}, context)

def contacto (request):
	context = RequestContext(request)
	if request.method == 'POST':
		nombre = request.POST['nombre']
		asunto = request.POST['asunto']
		mail = request.POST['mail']
		mensaje= request.POST['mensaje']
		email = EmailMessage(asunto, 'Nombre: '+nombre+"\n"+'Mail: '+mail+"\n\n"+mensaje, to=['piojotissera@gmail.com'])
		#email = EmailMessage(asunto, 'Nombre: '+nombre, to=['piojotissera@gmail.com'])
		email.send()        
	return render_to_response('Contactos.html', context)

def conversor (request):
	context = RequestContext(request)
	return render_to_response('CambioDeMoneda.html', context)

def calcu (request):
	context = RequestContext(request)
	return render_to_response('Calcu.html', context)

def crono (request):
	context = RequestContext(request)
	return render_to_response('Cronometro1.html', context)

def curriculum (request):
	context = RequestContext(request)
	return render_to_response('Curriculum.html', context)

def ver_post(request, id_post):
	context = RequestContext(request)
	mi_post = Entrada.objects.get(id=id_post)
	mensajes = Mensajes.objects.filter(published_in = mi_post, published = True) 
	return render_to_response('post.html', {'post':mi_post,'mensajes':mensajes},context)
	
def comentar(request):
	if request.method == 'POST':
		context = RequestContext(request)      
        	nombre = request.POST['nombre']
        	mensaje = request.POST['mensaje']   
        	id_post = request.POST['id']
        	comentario = Mensajes()
        	comentario.mensaje = mensaje        
        	comentario.nombre = nombre
        	comentario.published_in = Entrada.objects.get(id=id_post)
        	comentario.save()
        	comentarioReturn = {"nombre": comentario.nombre, "fecha": "Ahora", "mensaje":comentario.mensaje}
    		return HttpResponse(json.dumps(comentarioReturn), content_type="application/json")
	return


			
	

blog/templates/Calcu.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
        <br>
        <br>
        <br>
        <br>
        
        <div class="header">            
            <h1 align=center><font color = white>Calculadora</font></h1>
        </div> 
		
        <div class="tecladoNum">
			<input id="resultado" type="text" value=""/>
			<br>
            <input type="button" id="btn1" onclick="ejecutar(this)" value="1" />
            <input type="button" id="btn2" onclick="ejecutar(this)" value="2" />
            <input type="button" id="btn3" onclick="ejecutar(this)" value="3" />
            <input type="button" id="btnmas" onclick="ejecutar(this)" value="+" />
            <br>
            <input type="button" id="btn4" onclick="ejecutar(this)" value="4" />
            <input type="button" id="btn5" onclick="ejecutar(this)" value="5" />
            <input type="button" id="btn6" onclick="ejecutar(this)" value="6" />
            <input type="button" id="btnmenos" onclick="ejecutar(this)" value="-" />
            <br>
            <input type="button" id="btn7" onclick="ejecutar(this)" value="7" />
            <input type="button" id="btn8" onclick="ejecutar(this)" value="8" />
            <input type="button" id="btn9" onclick="ejecutar(this)" value="9" />
            <input type="button" id="btnpor" onclick="ejecutar(this)" value="*" />
            <br>
            <input type="button" id="btnp" onclick="ejecutar(this)" value="." />
            <input type="button" id="btn0" onclick="ejecutar(this)" value="0" />
            <input type="button" id="btne" onclick="ejecutar(this)" value="=" />
            <input type="button" id="btndiv" onclick="ejecutar(this)" value="/" />
            <br>
        </div>
	
	
{% endblock %}


/*--------------------------------------------------------------------------------------*/
{% block script %}
	<script>
	aux=0
	function ejecutar(botoncitodelacalculadorita) {
            aprieta = botoncitodelacalculadorita.value;
            val = document.getElementById("resultado").value;
             if (aux != 0){
		        if (aprieta=="1"||"2"||"3"||"4"||"5"||"6"||"7"||"8"||"9"){
		        	 document.getElementById("resultado").setAttribute("value",aprieta);
		        	 aux=0;
		        }
            }else{
            if (aprieta=="="){
                if (val.length!=0){
                    result = eval(val);
                document.getElementById("resultado").setAttribute("value",result);
                aux = 1;
                }
            }
           	else{ document.getElementById("resultado").setAttribute("value",val+aprieta);
            }
                    
			}
        }
/*--------------------------------------------------------------------------------------*/
  	</script>
{% endblock %}
</html>

blog/templates/CambioDeMoneda.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
		<div class="header">  
		<br>
		<br>
		<br>
		<br>          
            <h1 align=center><font color = white>Cambio de Moneda</font></h1>
        </div> 
		<br>

        <div class= "contentMoneda">
		    <select id="combo1">		
    
				<option value="Pesos">Pesos Arg</option>
				<option value="Euros">Euros</option>				
				<option value="Dolar">Dolar</option>
				<option value="Reales">Reales</option>
				<option value="Chilenos">Chilenos</option>
				<option value="Uruguayos">Uruguayos</option>
			</select>
			
		    
		    <input id="conver" type="text" value=""/>
		    <input id="resultado" type="text" value=""/>
		    
		    
		    <select id="combo2">
				<option value="Pesos1">Pesos Arg</option>
				<option value="Euros1">Euros</option>				
				<option value="Dolar1">Dolar</option>
				<option value="Reales1">Reales</option>
				<option value="Chilenos1">Chilenos</option>
				<option value="Uruguayos1">Uruguayos</option>
			</select>
		</div>
		<div class="teclasNoNum">
			<input type="button" id="Limpiar1" onclick="Limpiar(this)" value="Limpiar"/>
			<input type="button" id="Convertir" onclick="Convertir(this)" value="Convertir" />
		    <br>
		</div>
		<div class= "tecladoNum">
		    <input type="button" id="btn1" onclick="ejecutar(this)" value="1" />
		    <input type="button" id="btn1" onclick="ejecutar(this)" value="2" />
		    <input type="button" id="btn1" onclick="ejecutar(this)" value="3" />
		    <br>
		    <input type="button" id="btn1" onclick="ejecutar(this)" value="4" />
		    <input type="button" id="btn1" onclick="ejecutar(this)" value="5" />
		    <input type="button" id="btn1" onclick="ejecutar(this)" value="6" />
		    <br>
		    <input type="button" id="btn1" onclick="ejecutar(this)" value="7" />
		    <input type="button" id="btn1" onclick="ejecutar(this)" value="8" />
		    <input type="button" id="btn1" onclick="ejecutar(this)" value="9" />
		</div> 
		    <br>
		    <br>
		    <br>
		<div class="botonTroll">
		    <b>¿No le gusta?</b>
			<br>
        	<input type="button" id="Chistoso" onmouseover="Joder(this)" value="Queja"/>
		</div>
			
{% endblock %}
{% block script %}
	<script>
/*valores de conversión con referencia pesos
pesos=1;
euro=9.5;
dolar=8.8;
reales=2.9;
chilenos=0.01;
uruguayos=0.3;
*/
	var valores=[1,9.5,8.8,2.9,0.01,0.3]
		function ejecutar(botoncito) {
            aprieta = botoncito.value;
            val = document.getElementById("conver").value;
		        if (aprieta=="1"||"2"||"3"||"4"||"5"||"6"||"7"||"8"||"9"){
		        	 document.getElementById("conver").value=("value",val+aprieta);
		        }	
        }
/*--------------------------------------------------------------------------------------*/        
        function Limpiar(boton){
        	aprieta = boton.value;
        		if (aprieta=="Limpiar"){
        			document.getElementById("conver").value=("value","");
        			document.getElementById("resultado").value=("value","");        			
        		}
    		}
/*--------------------------------------------------------------------------------------*/
    	function Convertir(btn){
    		aprieta = btn.value;
    		val1 = document.getElementById("conver").value;
    			if(aprieta=="Convertir"){     			
    				var cuadroTxt= parseFloat(document.getElementById("conver").value);
    				
    				var monedaPasada = document.getElementById("combo1").selectedIndex;         	
    				var monedaAPasar = document.getElementById("combo2").selectedIndex;    				
					var resultado1 = (valores[monedaPasada]*cuadroTxt)/valores[monedaAPasar];
					
    				document.getElementById("resultado").value=("value",resultado1);
    				
    			}
    		}
/*--------------------------------------------------------------------------------------*/
    	function Joder(btn1){
    		aprieta=btn1.value;
    		if (aprieta=="Queja"){
 				document.getElementById("Chistoso").style.margin="0px 100px";
 				document.getElementById("Chistoso").value="Si no te gusta";
			}
			if (aprieta=="Si no te gusta"){
				document.getElementById("Chistoso").style.margin="0px -100px";
				document.getElementById("Chistoso").value="Jodete";
			}
			if (aprieta=="Jodete"){
				document.getElementById("Chistoso").style.margin="0px 100px";
				document.getElementById("Chistoso").value="Si no te gusta";
			}
    	}
/*--------------------------------------------------------------------------------------*/
	</script>
{% endblock %}
	
</html>

blog/templates/Contactos.html
<html>


{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
        <div class="header">            
            <h1 align=center><font color = white>Contactanos</font></h1>
        </div>

		
        <form action="" method="POST" name="sentMessage" id="contactForm">
            <form class='contacto'>
            {% csrf_token %} 
            <div><label>Nombre:</label><input type='text' name="nombre" value=''></div>
            <div><label>E-Mail:</label><input type='text' name="mail"value=''></div>
            <div><label>Asunto:</label><input type='text' name="asunto"value=''></div>
            <div><label>Mensaje:</label><textarea rows='6' name="mensaje"></textarea></div>
            <div><input type='submit' value="Envia Mensaje"></div>
        </form>

        </div>  
        
{% endblock %}
	
	
		
	
</html>

blog/templates/Cronometro1.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<br>
<br>
<br>
<br>
<div class="contentCrono">
<font color = white>
<h1>Contador de vueltas</h1>
	<h2 id='crono'>00:00:00</h2>
</font>
	<input type="button" value="Empezar" onclick="empezarDetener(this);">
	<input type="button" value="Vuelta" id="vuelta" onclick="mostrarValorActual();" disabled>
</div>

<div id="tiempos"><div></div></div>
{% endblock %}



{% block script %}

<script>
/*--------------------------------------------------------------------------------------*/
	var inicio=0;
	var vuelta=0;
	var timeout=0;
 
	function empezarDetener(elemento)
	{
		if(timeout==0)
		{
			elemento.value="Detener";
			inicio=vuelta=new Date().getTime();
			document.getElementById("tiempos").innerHTML="<div></div>";
			funcionando();
			document.getElementById("vuelta").disabled=false;
		}else{
			elemento.value="Empezar";
			document.getElementById("vuelta").disabled=true;
			clearTimeout(timeout);
			timeout=0;
		}
	}
/*--------------------------------------------------------------------------------------*/
 
	function funcionando()
	{
		var actual = new Date().getTime();
		var diff=new Date(actual-inicio);
 

		var result=LeadingZero(diff.getUTCHours())+":"+LeadingZero(diff.getUTCMinutes())+":"+LeadingZero(diff.getUTCSeconds());
		document.getElementById('crono').innerHTML = result;
 
		timeout=setTimeout("funcionando()",1000);
	}
 /*--------------------------------------------------------------------------------------*/
	/**
	 * Función que muestra cada vuelta
	 */
	function mostrarValorActual()
	{

		var actual=new Date().getTime();
		var diff=new Date(actual-vuelta);
 

		vuelta=new Date().getTime();
 
		var ultimo=document.createElement("div");
		ultimo.innerHTML=LeadingZero(diff.getUTCHours())+":"+LeadingZero(diff.getUTCMinutes())+":"+LeadingZero(diff.getUTCSeconds())+","+diff.getUTCMilliseconds();
 

		document.getElementById("tiempos").insertBefore(ultimo,document.getElementById("tiempos").getElementsByTagName("div")[0]);
	}
 
/*--------------------------------------------------------------------------------------*/
	function LeadingZero(Time) {
		return (Time < 10) ? "0" + Time : + Time;
	}
/*--------------------------------------------------------------------------------------*/

	</script>
{% endblock %}
</html>

blog/templates/Curriculum.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
		<br>
		<br>
		<br>
        <div class="header">            
		  <h1 align=center><font color = white>Curriculum Vitae</font></h1>
        </div>
		<div class="content1">
            <img src = "{% static 'css/img/descarga.jpg' %}"></img>    
        
			<h3><font color = white>Datos Personales</font></h3>
        
         	<table>
                    <tr>
                        <td><strong>Apellido:</strong></td>
                        <td>Alvarez</td>
                    </tr>
                    <tr>
                        <td><strong>Nombre</strong></td>
                        <td>Bonefacio</td>
                    </tr>
                    <tr>
                        <td><strong>Fecha de nacimiento:</strong></td>
                        <td>08/02/1998</td>
                    </tr>
                    <tr>
                        <td><strong>DNI:</strong></td>
                        <td>30.300.300</td>
                    </tr>
                    <tr>
                        <td><strong>Sexo:</strong></td>
                        <td>Masculino</td>
                    </tr>
                    <tr>
                        <td><strong>Dirección:</strong></td>
                        <td>Villa los Aromos Los nogales 360</td>
                    </tr>
                    <tr>
                        <td><strong>Teléfono:</strong></td>
                        <td>153453593</td>
                    </tr>
                    <tr>
                        <td><strong>E-mail:</strong></td>
                        <td>Maestruli@gDuro.com</td>
                    </tr>
                </table>

		<h3><font color = white>Formación Académica<font></h1>
		<table>
			<tr>
				<td><strong>Colegio Secundario:</strong></td>
				<td>ITS Villada</td>
			</tr>
			<tr>
				<td><strong>Experto:</strong></td>
				<td>La conjetura postdadaísta, la dialéctica yuxtaposicional y las teorías de Jung</td>
			</tr>	
			
        </div>
       	
{% endblock %}
		
</html>

blog/templates/SitioWebHoshible.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
	<br>
	<br>
	<br>
	<br>
        <div class="header">            
            <h1 align=center><font color = white>Sitio Web Hoshible</font></b></h1>
            <b><font color = white>El pasaje estándar Lorem Ipsum, usado desde el año 1500.</font></b>
	    
			<br>
			<br>

        </div>

	<div class="content">
 		<div style="height: 200px; width: 200px;"><img src="{% static 'img/01.jpg' %}" id="image" width=200 height = 200 ALIGN=right /></div>
		<progress id="bar" value="0" max="100"></progress>
	</div>


	{% for post in posts %}
        <div class="content">
		<a href="{% url 'app_blog:vermipost' post.id %}">
		<h2 class="post-title">
			{{post.titulo}}
		</h2>
                <h3 class="post-subtitle">
                	{{post.resumen}}
                </h3>
		</a>
		<hr>
	</div>
        {% endfor %}
		
            
	{% endblock %}

	{% block script %}
        <script>
 	var images = ["./static/img/01.jpg","./static/img/02.jpg","./static/img/03.jpg","./static/img/04.jpg","./static/img/05.jpg","./static/img/06.jpg"];
        var tiempo = setInterval(function(){load();},1000);

        $(document).ready(function(){
            load();
        });

        var por = document.getElementById("bar");
        var img = document.getElementById("image");
        a = 0;
        var time = setInterval(load, 50);

        function load(){
            a ++;
            por.value = a;
            if (por.value == 100){
                a = 0;
                por.value = a;
                var i = Math.round(Math.random()*5);
                img.setAttribute("src",images[i]);
            }
        }
		</script>
	{% endblock %}
	</body>
	

	
</html>

blog/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>

    <meta charset="utf-8">

	<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="{% static 'css/Style.css' %}"type="text/css">
	<link rel="stylesheet" href="{% static 'css/StyleCalculadora.css' %}"type="text/css">
	<link rel="stylesheet" href="{% static 'css/StyleCambioMoneda.css' %}"type="text/css">
	<link rel="stylesheet" href="{% static 'css/StyleCronómetro.css' %}"type="text/css">

	<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="topbar"></div>
            <ul class="topMenu">
				<li>
				    <a href="{% url 'app_blog:home' %}"><i class="fa fa-home"></i>Inicio</a>
				</li>
				<li>
				    <a href="{% url 'app_blog:contacto' %}"></i>Contactanos</a>
				</li>
				<li>
				    <a href="{% url 'app_blog:conversor' %}"><i class="fa fa-money"></i>Conversor</a>
				</li>
				<li>
				    <a href="{% url 'app_blog:calcu' %}"><i class="fa fa-calculator"></i>Calculadora</a>
				</li>
				<li>
				    <a href="{% url 'app_blog:crono' %}"><i class="fa fa-clock-o"></i>Cronometro</a>
				</li>
				<li>
				    <a href="{% url 'app_blog:curriculum' %}"><i class="fa fa-briefcase"></i>Curriculum</a>
				</li>                   
				<li>
				    <a href="{% url 'admin:index' %}">Admin</a>
				</li>                    
			</ul>
		</div>

{% block css %}    
{% endblock %}
</head>

<div class="container">
{% block content %}
{% endblock %}
        
</div>
<!-- jQuery -->
<script src="{% static 'js/jquery-2.1.4.js' %}"></script>
</body>

{% block script %}
{% endblock %}

</html>

blog/templates/post.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}

       
{% endblock %}

{% block content %}
	<br>
	<br>
	<br>
	<br>
<div class="content">
<article>
	<a href="{% url 'app_blog:home' %}"><i class="fa fa-home"></i>Atras</a>
	<h2 class="section-heading">{{post.titulo}}</h2>
	<h3 class="section-heading">{{post.fecha}}</h3>
	<p>{{post.contenido}} </p>
	{% csrf_token %} 

</article>
</div>
 <div id="mensajes">
                {% for comentario in mensajes %}
                <h5>{{comentario.nombre}}</h5>
                <small>{{comentario.fecha}}</small>
                <p>{{comentario.mensaje}}</p>
                <hr>
                {% endfor %}
    </div>
<div class="content">

<div><label>Tu Nombre:</label><input type='text' id="nombre" value=''></div>
<div><label>Comentario:</label><textarea rows='6' id="comentario"></textarea></div>
<input type="button" id="send" value="Comentar" />
</div>

{% endblock %}
{% block script %}
<script>
	$("#send").click(function(){
		console.log("tu vieja")
		var data={
			csrfmiddlewaretoken:'{{ csrf_token }}',
			nombre: $("#nombre").val(),
			mensaje: $("#comentario").val(),	
			id:'{{post.id}}	',
		}
		$.ajax({
			method: "POST",
			url: "{% url 'app_blog:comentar' %}",
			data:data,
			success:function(result){
                		$("#mensajes").prepend("<h5>"+result.nombre+"</h5><small>"+result.fecha+"</small><p>"+result.mensaje+"</p><hr>");
				$("#nombre").attr("value","");
				$("#comentario").attr("value","");
			},
			error: function(e){
				console.log("ERRRORRRR");
				console.log(e.responseText);
			}
		});
	}); 

</script>
{% endblock %}

blog/templates/test.html
<html>
<body>
<p>
hola ulises puto
</p>
</body>
</html>